
let baseDePreguntas = [
  {
    pregunta: "¿Cuál fue el primer movimiento feminista que surgió en Paraguay?",
    ayuda: "Nació a sugerencia del diputado republicano Telémaco Silvera en 1920.",
    respuesta: "Centro Feminista Paraguayo",
    distractores: ["Centro Feminista Paraguayo","Asociación Feminista","Consejo de Mujeres del Paraguay","Unión Feminista del Paraguay"],
  },
  {
    pregunta: "¿En qué siglo se inició la Revolución Industrial?",
    ayudaImg: "imag/BASF-Werk-Ludwigshafen-1881.jpg",
    ayuda: "Aproximadamente hacia el año 1760, concluyó en la década de 1840 y se limitó principalmente a Gran Bretaña.",
    respuesta: "XVIII",
    distractores: ["XVIII","XIV","XV","XX"],
  },
  {
    pregunta: '"_________son formas de participación de la ciudadanía en la sociedad, que se organiza para actuar colectivamente e impulsar el logro de objetivos comunes." Completa la frase:',
    respuesta: "Movimientos Sociales",
    distractores: ["Movimientos Sociales","Drotinas Sociales","Nacionalismo","Proletario"],
  },
  {
    pregunta: "¿Cuál de estas obras corresponden al gobierno de Bernardino Caballero?",
    ayudaImg: "imag/Bernardino-Caballero.jpg",
    respuesta: "Creó el Registro Civil de las Personas (1890), La Escuela de Derecho (1884)",
    ayuda: "Fue presidente de Paraguay de 1886 a 1890.",
    distractores: ["Creó el Registro Civil de las Personas (1890), La Escuela de Derecho (1884)","Creó La ley de Contribucion Directa","Se fortableció la Guardia Nacional","Se sancionó la Ley del Matrimonio Civil, en 1898"],
  },
  {
    pregunta: 'Durante el gobierno de quién "se fundaron los partidos políticos: el Centro Democrático y la Asociación Nacional Republicana (1887)"',
    ayudaImg: "imag/escobar2.jpg",
    ayuda: "Fue presidente de Paraguay de 1886 a 1890.",
    respuesta: "Patricio Escobar",
    distractores:["Patricio Escobar","Emilio Aceval","Manuel Domingiez","Juan Bautista Egusquiza"],
  },
  {
    pregunta: "Según el Liberalismo, ¿a qué tienen derecho las personas?",
    respuesta: "El derecho a la vida y a la libertad.",
    distractores:["El derecho a la vida y a la libertad.","Censura y vigilancia, Pobreza.","Desplazamiento forzado, La Libertad.","Corrupción, Derecho a la vida."],
  },
  {
    pregunta: "¿Cuál opción pertenece a un hecho del Nacionalismo en Paraguay?",
    ayuda: "El nacionalismo paraguayo se confunde con la exaltación de la figura de Francisco Solano López.",
    respuesta: "La Guerra de la Triple Alianza, Revolución de Mayo.",
    distractores: ["La Guerra de la Triple Alianza, Revolución de Mayo.","Conflictos internos, Revolución de Mayo.","Influencias externas, Líderes carismáticos.","La Guerra de la Triple Alianza, Conflictos internos."],
  },
  {
    pregunta: '"Fue fundado el 11 de diciembre de 1951." Corresponde a la fecha importante de:',
    ayuda: "Es un partido político paraguayo que tiene su origen en la Revolución del 17 de febrero de 1936.",
    respuesta: "Fundación del Partido Revolucionario Febrerista.",
    distractores:["Fundación del Partido Revolucionario Febrerista.","La Independencia","Tratado de paz del Chaco.","Segunda Guerra Mundial."],
  },
  {
    pregunta: "¿A consecuencia de qué surge el proletario?",
    ayudaImg: "imag/Pyramid_of_Capitalist_System.jpg",
    ayuda: "Se refería a aquel ciudadano pobre que solamente con su prole podía servir al Estado.",
    respuesta: "Revolución Industrial.",
    distractores: ["Revolución Industrial.","Diversidad cultural y étnica.","Ideologías y políticas contrarias.","Expropiación de tierras."],
  },
  {
    pregunta: '"________es un movimiento social y político que busca la igualdad de género y la eliminación de la discriminación de género en todas sus formas." Completa la frase:',
    ayuda:"",
    respuesta: "Feminismo",
    distractores: ["Feminismo","Movimientos Sociales","Principios del Liberalismo","Movimientos estudiantiles"],
  },
  {
    pregunta: '"___________es un actor político colectivo que juega un rol movilizador y de fomento del cambio social, a través de acciones de contenido simbólico e identitario, a menudo poco convencionales." Completa la frase:',
    ayuda:"",
    respuesta: "Movimientos Sociales" ,
    distractores: ["Movimientos Sociales","Feminismo","Principios del Liberalismo","Partidos Tradicionales"],
  },
  {
    pregunta: '"___________son iniciativas colectivas lideradas por estudiantes que buscan promover cambios en el sistema educativo, así como en la sociedad en general." Completa la frase:',
    ayuda:"",
    respuesta: "Movimientos estudiantiles",
    distractores: ["Movimientos estudiantiles","Movimientos Sociales","Principios del Liberalismo","Partidos Tradicionales"],
  },
  {
    pregunta: "¿En qué fecha y año se fundaron los Partidos Tradicionales?",
    ayuda:"",
    respuesta: "El 11 de septiembre de 1887 y el 10 de julio de 1887.",
    distractores: ["El 11 de septiembre de 1887 y el 10 de julio de 1887.","El 10 de agosto de 1836 y El 11 de septiembre de 1887.","El 17 de septiembre de 1836 y el 15 de noviembre de 1849.","El 10 de julio de 1887 y el 12 de agosto de 1848."],
  },
  {
    pregunta: '"____________es una corriente de pensamiento político y filosófico que aboga por la libertad individual, los derechos humanos, la igualdad de oportunidades, la limitación del poder del gobierno y la protección de la propiedad privada." Completa la frase:',
    ayudaImg: "imag/COLORADO-Y-LIBERAL.jpg",
    ayuda:"",
    respuesta: "Principios del Liberalismo",
    distractores: ["Movimientos Sociales","Principios del Liberalismo","Partidos Tradicionales"],
  },
  {
    pregunta: "¿Qué guerras se produjeron durante la Hegemonía Liberal?",
    ayuda:"",
    respuesta: "Guerra Civil, Guerra del Chaco",
    distractores: ["Guerra Civil, Guerra del Chaco","Guerra Federal, Guerra del Chaco","Guerra del Chaco, Guerra Federal","Revolución Industrial, Guerra Civil"],
  },
  {
    pregunta: "¿A cuál opción pertenece una clasificación de los movimientos sociales?",
    ayudaImg: "imag/20160602170250_hc-flas.jpeg",
    respuesta: "Por su duración, alcance de sus reclamos y por la cantidad de integrantes.",
    distractores: ["Por su duración, alcance de sus reclamos y por la cantidad de integrantes.","La igualdad de derechos civiles y políticos para grupos específicos.","Se centran en la protección y promoción de los derechos humanos fundamentales.","Luchan por la conservación del medio ambiente y la sostenibilidad."],
  },
  {
    pregunta: "¿En qué fecha surge el primer Movimiento Femenista Paraguayo?",
    ayudaImg: "imag/Imagen-central-MUJER-PYA.jpeg",
    respuesta: "El 20 de julio de 1848",
    distractores: ["El 20 de julio de 1848","El 15 de agosto de 1836","El 20 de junio de 1848","El 10 de mayo de 1849"],
  },
  {
    pregunta: "¿Quién es considerada la primera feminista paraguaya?",
    ayudaImg: "imag/CtZjDhpWYAEjPdN.jpg",
    respuesta: "Dra. Serafina Dávalos",
    distractores: ["Dra. Serafina Dávalos","Juana María de Lara","Elisa Alicia Lynch","Carmen Casco de Lara Castro"],
  },
  {
    pregunta: "¿Cuántos presidentes tuvo Paraguay desde 1949 hasta 1954?",
    ayuda:"",
    respuesta: "6 presidentes",
    distractores: ["6 presidentes","4 presidentes","7 presidentes","5 presidentes"],
  },
  {
    pregunta: "La frase 'las luchas son de los fuerte, los débiles solo se quejan' corresponde a:",
    ayuda:"",
    respuesta: "Bernardino Caballero",
    distractores: ["Bernardino Caballero","Dr. Francia","Don Carlos A. Lopez","Alfredo Stroessner"],
  }
];