let baseDePreguntas = [
  {
    pregunta: "¿Cuál ciudad es conocida como la Madre de ciudades en Paraguay?",
    ayuda:"",
    ayudaImg: "imag/asuncion.jpg",
    ayuda: "Fue llamada así por los españoles, ya que se convirtió en el centro de toda la provincia. De sus puertos salían expediciones para fundar otras ciudades.",
    respuesta: "Asunción",
    distractores: ["Luque", "Villarrica", "Encarnación"],
  },
  {  
    pregunta: "¿Quién estableció el primer asentamiento estable en lo que hoy es Paraguay?",
    ayudaImg: "imag/Domingo_Martínez_de_Irala.jpg",
    ayuda: "Fue un conquistador español que lideró la primera expedición a la región del Paraguay.",
    respuesta: "Domingo Martínez de Irala",
    distractores: ["José Gaspar Rodríguez de Francia", "Carlos Antonio López", "Alfredo Stroessner"],
  },
  {
    pregunta: "¿Cómo se conoce la unión entre españoles y nativos americanos durante la colonia en Paraguay?",
    ayuda: "Este proceso de mezcla de razas tuvo gran influencia en la sociedad y cultura paraguaya.",
    respuesta: "Mestizaje",
    distractores: ["Casamiento", "Aculturación", "Convivencia"],  
  },
  {
    pregunta: "¿Quién fundó el Fuerte de Nuestra Señora de la Asunción?", 
    ayudaImg:"imag/juan de salazar.jpg",
    ayuda: "Fue un conquistador español clave en los inicios de la colonización del Paraguay.",
    respuesta: "Juan de Salazar y Espinoza",
    distractores: ["Domingo Martínez de Irala", "José Gaspar Rodríguez de Francia", "Carlos Antonio López"],
  },
  {
    pregunta: "¿A quién corresponde este personaje: nació en Asunción, falleció en Santa Fe, fue un hábil militar y hombre de serena visión?",
    ayudaImg: "imag/hernandarias.jpg",
    ayuda: "Desempeñó un papel clave en la fundación de varias ciudades en la región del Río de la Plata.", 
    respuesta: "Hernando Arias de Saavedra",
    distractores: ["José Gaspar Rodríguez de Francia", "Francisco Solano López", "Bernardino Caballero"],
  },
  {
    pregunta: "¿En qué trágica batalla contra la Triple Alianza murió gran parte de la población masculina paraguaya?",
    ayudaImg: "imag/Día-del-Niño-en-Paraguay-Batalla-de-Acosta-Ñu-3-1024x576.jpg",  
    ayuda: "Fue un punto de inflexión en la Guerra de la Triple Alianza contra Paraguay entre 1864 y 1870.",
    respuesta: "Batalla de Acosta Ñu",
    distractores: ["Batalla de Boquerón", "Batalla de Humaitá", "Batalla de Curupayty"],
  },
  {
    pregunta: "¿Qué importante evento ocurrió en Paraguay en la madrugada del 14 y 15 de mayo de 1811?",
    ayudaImg: "imag/14 y 15 de mayo.jpeg",
    ayuda: "Marcó el inicio del proceso independentista paraguayo respecto a España.",
    respuesta: "Independencia de Paraguay",
    distractores: ["Primer Gobierno Patrio", "Instalación del Consulado", "Revolución de 1947"],
  },
  {
    pregunta: "¿Quién fue un prócer de la Independencia de Paraguay en 1811?",
    ayuda: "Fue un destacado participante en el movimiento revolucionario de Mayo de 1811 en Paraguay.",
    respuesta: "Vicente Ignacio Iturbe",
    distractores: ["Blas José Rojas", "Carlos Antonio López", "Gaspar Rodríguez de Francia"],
  }, 
  {
    pregunta: "¿Qué organismo de gobierno surgió en Paraguay tras la Revolución de Mayo de 1811?", 
    ayuda: "Fue establecido como resultado de la independencia de Paraguay de España en 1811.",
    respuesta: "El Triunvirato de 1811",
    distractores: ["Consulado", "Junta de Sanamiento", "Dictadura Perpetua"],
  },
  {
    pregunta: "¿Quién fue esta importante figura histórica paraguaya: Nació en Asunción en 1766, participó en la Revolución de Mayo de 1811 y gobernó como Dictador Supremo hasta 1840?",
    ayuda: "Fue una figura central en el proceso independentista paraguayo y su política en el siglo XIX.",
    respuesta: "José Gaspar Rodríguez de Francia",
    distractores: ["Carlos Antonio López", "Alfredo Stroessner", "Andrés Rodríguez"],
  },
  {
    pregunta: "¿Quién gobernó Paraguay con un régimen autoritario entre 1954 y 1989?",
    ayuda: "Fue una de las dictaduras militares más largas del siglo XX en América Latina.",
    respuesta: "Alfredo Stroessner", 
    distractores: ["Rutherford B. Hayes", "Higinio Morínigo", "Juan Natalicio González"],
  },
  {
    pregunta: "¿Qué importantes obras materiales se construyeron durante el gobierno de Carlos Antonio López?",
    ayudaImg: "imag/don carlos.jpg",
    ayuda: "Impulsó un ambicioso plan de desarrollo de infraestructura en Paraguay.",
    respuesta: "El Palacio de López, la Catedral y la Estación del Ferrocarril",
    distractores: ["La Represa de Itaipú", "La Ruta Transchaco", "El Puente de la Amistad"],
  },
  {
    pregunta: "¿Cuáles fueron algunas de las capitales paraguayas durante la Guerra Grande contra la Triple Alianza?",
    ayudaImg: "imag/regular_triplealuh.jpg.jpg",
    ayuda: "Ante el avance enemigo, el gobierno paraguayo se vio forzado a trasladar la capital varias veces.",
    respuesta: "Asunción, Luque, Piribebuy y Curuguaty",
    distractores: ["Asunción, Villarrica, Caazapá y Ciudad del Este", "San Lorenzo, Lambaré, Mariano Roque Alonso y Paraguarí", "Encarnación, Coronel Oviedo, Caacupé y San Pedro"],
  }, 
  {
    pregunta: "¿Cuáles fueron las principales etapas de la Guerra Grande (Guerra de la Triple Alianza)?",
    ayuda: "El conflicto tuvo una progresión que puede dividirse en fases.",
    respuesta: "Ofensiva y defensiva",
    distractores: ["Intervención extranjera", "Consecuencias y paz", "Invasión y resistencia"],
  },
  {
    pregunta: "¿Entre qué años tuvo lugar la Guerra del Chaco entre Paraguay y Bolivia?",
    ayudaImg: "imag/Mapa_de_la_Guerra_del_Chaco_es.svg.png",
    ayuda: "Fue un conflicto armado por el control del territorio del Chaco Boreal.",
    respuesta: "1932 y 1935",
    distractores: ["1922 y 1925", "1942 y 1945", "1952 y 1955"],
  },
  { 
    pregunta: "¿Quién fue el presidente paraguayo durante la Guerra de la Triple Alianza?",
    ayuda: "Lideró la defensa de Paraguay ante la invasión de Brasil, Argentina y Uruguay.",
    respuesta: "Francisco Solano López",
    distractores: ["Carlos Antonio López", "José Gaspar Rodríguez de Francia", "Alfredo Stroessner"],
  },
  {
    pregunta: "¿Qué proceso histórico desencadenaron la falta de participación política, los monopolios y los impuestos abusivos en Paraguay?",
    ayuda: "El descontento de la población paraguaya con estas condiciones derivó en un hito trascendental.", 
    respuesta: "La independencia de España",
    distractores: ["La Guerra del Chaco", "La Guerra Grande", "La revolución de 1947"],
  },
  {
    pregunta: "¿En qué fecha se firmó el tratado que puso fin a la Guerra del Chaco entre Paraguay y Bolivia?",
    ayuda: "La contienda armada terminó con la firma de un acuerdo de paz entre los países beligerantes.",
    respuesta: "12 de junio de 1935",
    distractores: ["14 de mayo de 1811", "1 de marzo de 1870", "5 de agosto de 1932"],
  },
  {
    pregunta: "¿A qué conflicto corresponde esta descripción?: Fue una guerra que tuvo lugar principalmente en Uruguay y Argentina durante las décadas de 1830 y 1840.",
    ayuda: "Enfrentó a distintos grupos políticos y se extendió desde el Río de la Plata hasta el sur de Brasil.",
    respuesta: "La Guerra Grande (Guerra de la Triple Alianza)",
    distractores: ["Guerra del Chaco", "Guerra del Paraguay", "Revolución de 1947"],
  },
  {
    pregunta: "¿Qué país desempeñó un rol decisivo en la victoria paraguaya en la Guerra contra la Triple Alianza?",
    ayuda: "Aportó apoyo militar clave que cambió el curso del conflicto en favor de Paraguay.",
    respuesta: "Estados Unidos", 
    distractores: ["Argentina", "Brasil", "Bolivia"] 
  }
];