let baseDePreguntas = [
  {
    pregunta: "¿En qué siglo tuvo lugar el Renacimiento?",
    respuesta: "Entre los siglos XIV y XVI.",
    distractores: ["Entre los siglos XVI y XVII", "Entre los siglos XVII y XIX", "Entre los siglos XIX y XX"],
  },
  {
    pregunta: "¿Cuál es la cuna del renacimiento?",
    ayudaImg: "imag/italia.jpg",
    ayuda:"Se expandió por toda Europa, donde florecieron algunas de las obras de arte, la literatura y la cultura más destacadas de la época.",
    respuesta: "Italia.",
    distractores: ["Francia.", "España.", "Inglaterra."],
  },
  {
    pregunta: "Según tus conocimientos, ¿quiénes conforman el mundo clásico?:",
    ayuda:"",
    ayudaImg: "imag/roma.jpg",
    respuesta: "Las civilizaciones de Grecia y Roma.",
    distractores: ["Civilizaciones mesopotámicas, como Babilonia y Asiria.","Civilizaciones de Egipto Antiguo.","El Imperio Persa.", ],
  },
  {
    pregunta: "Según lo aprendido, ¿cuáles son las pricipales construcciones de roma?",
    ayudaImg: "imag/hormigon-romano.jpg",
    respuesta: "Templos, basílicas, palacios.",
    distractores: ["Los monumentos, las estatuas y los acueductos","los gimnacios, las vias y los templos", "los arcos, las esculturas y las estancias."],
  },
  {
    pregunta: "La apreciación de la belleza y perfección del cuerpo humano plasmada en la escultura griega se conoce como:",
    ayudaImg: "imag/escultura griega.jpg",
    respuesta: "Escultura.",
    distractores: ["Fisicultura", "Pintura.", "Arquitectura."],
  },
  {
    pregunta: "¿Cómo era considerado Jesús?",
    ayudaImg: "imag/jesús.jpg",
    respuesta: "Era considerado como el mesias por los profetas hebreos y como el hijo de Dios.",
    distractores: ["Líder religioso judío", "Revolucionario.", "Profeta de Dios.",],
  },
  {
    pregunta: " ̈___________fue un movimiento de caracter religioso, realizado en Alemania en el siglo XVI. ̈",
    ayudaImg: "imag/Reforma-Protestante.jpg",
    ayuda:"Además, tuvo un impacto duradero en la historia religiosa y política de Europa y más allá, y su legado continúa siendo relevante en la actualidad.",
    respuesta: "Reforma protestante",
    distractores: [ "Renacimiento.", "Humanismo.","Contrarreforma",],
  },
  {
    pregunta: "Según tu parecer, ¿en qué consistió la reforma de la Iglesia Católica?",
    ayuda:"Fue un movimiento que tuvo un impacto duradero en la religión y la historía europea, y su legado continúa influyendo en la diversidad religiosa actual.",
    respuesta: "Afirmó la validez de los siete sacramentos de la iglesia, la salvación por a fé y la existencia del purgatorio así creo compañia de Jesús.",
    distractores: ["Fue la institución religiosa dominante en Europa durante siglos.","Llevó al surgimiento de diversas ramas del protestantismo", "Una revolución religiosa.",],
  },
  {
    pregunta: "Dado en clase, humanismo se refiere a:",
    ayudaImg: "imag/humanismo.jpg",
    ayuda:"Fue un movimiento intelectual durante el Renacimiento que promovió el estudio de las humanidades.",
    respuesta: "Fue la manifestación filosófica, literaria y artística del renacimiento, con profunda admiración a los autores griegos y latinos.",
    distractores: [ "El auge del arte, la arquitectura y la música.","A un movimiento intelectual artístico y literario surgido en Francia.", "Al nacimiento de la democracia.", ],
  },
  {
    pregunta: " ̈Se originó y se desarrolló en el siglo XVIII, se utilizó la razón para utilizar la relidad del mundo, se buscó la libertad de personas, asi cómo elevar el nivel cultural de la sociedad.  ̈. Corresponde a:",
    ayudaImg: "imag/Ilustración-e1546974731901.jpg",
      ayuda:"Fue un movimiento intelectual y cultural que se desarrolló en Europa, principalmente durante los siglos XVII y XVIII, aunque sus raíces se encuentran en el Renacimiento y sus influencias se extendieron hasta el siglo XIX.",
    respuesta: "Ilustración.",
    distractores: ["Absolutismo.", "Democracia.", "Enciclopedia."],
  },
  {
    pregunta: " ̈__________Surgió a principios del siglo XVII y XVIII, fue una droctina política y económica que adquirió carácter revolucionario frente al absolutismo, tenía su punto de referencia en la libertad individal. ̈",   
    ayudaImg: "imag/liberalismo.jpg",
    ayuda:"Es una filosofía política y económica que ha influido en gran medida en la organización de las sociedades democráticas modernas. ",
    respuesta: "Lberalismo.",
    distractores: ["Ilustración.", "Democracia.", "Nacionalismo."],
  },
  {
    pregunta: "Según lo aprendido, ¿quién fue el máximo representante del Absolutismo?",
    ayudaImg: "imag/luis xiv.jpg",
    ayuda:"",
    respuesta: "Luis XIV.",
    distractores: ["Carlos V de España.","Federico II de Prusia.","Isabel II de Inglaterra.",],
  },
  {
    pregunta: "¿Cuáles fueron la corrientes intelectuales surgidas en el siglo XIX?",
    ayuda:"Fue testigo de una serie de corrientes intelectuales significativas que influyeron en gran medida en la cultura, la política y la sociedad de la época. ",
    respuesta: "Liberalismo, Nacionalismo.",
    distractores: [ "Democracia y Liberalismo", "Dictadura y Comunismo.", "Socialismo y Nacionalismo.",],
  },
  {
    pregunta: "¿Cuál de estas opciones corresponde a una causa de la Revolución Francesa?",
    ayuda:"",
    respuesta: "La influencia de la Ilustración.",
    distractores: ["La Democracia.", "Discriminación.", "Dictadura."],
  },
  {
    pregunta: "Según lo aprendido, ¿indica cuáles son los principios de la Revolución Fransesa?:",
    ayuda:"",
    respuesta: "Libertad, Fraternidad, Igualdad y Justicia",
    distractores: ["Honestidad y Amor","Libertad y Solidaridad","Libertad, Igualdad, Perseverancia y Amistad",],
  },
  {
    pregunta: "Según lo aprendido, ¿indica cuáles corresponde a la Primera Guerra Mundial?:",
    ayuda:"",
    respuesta: "Guerra de Movimientos y Guerra de Trincheras.",
    distractores: ["Batallas en el Frente Oriental y Occidental.","La Revolución Rusa y la Revolución francesa.","Participación de otras potencias.",],
  },
  {
    pregunta: " ̈_________la ciencia que estudia el pasado,para entender el presente y proyectar el futuro. Se refiere a:",
    ayuda:"",
    respuesta: "Historia.",
    distractores: ["Economía.", "Sociología.", "Geografía."],
  },
  {
    pregunta: " ̈_______fue la manifestación filosófica del renacimiento ̈. Corresponde a:",
    ayuda:"",
    respuesta: "Humanismo.", 
    distractores: ["Reforma.", "Contrarreforma.", "Liberalismo."],
  },
  {
    pregunta: "Según tus conocimientos, ¿indica cuáles son los períodos de la Historia Romana?:",
    ayuda:"",
    respuesta: "Monarquía, República e Imperio.",
    distractores: ["Democracia, República y Dictadura.","Comunismo, Socialismo e Imperio.","Dictadura, Monarquía y Democracia.",],
  },
];